# Generated by Django 3.2.6 on 2021-08-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiztaker',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='user',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='quiz_taker',
            field=models.CharField(default=None, max_length=100, verbose_name='Employee'),
        ),
    ]
