# Generated by Django 3.2.6 on 2021-08-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210817_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztaker',
            name='quiz_taker',
            field=models.CharField(max_length=100, verbose_name='Employee'),
        ),
    ]
